matrix:
  include:
  - language: go
    go: 1.13.x
  - language: go
    go: 1.14.x

env:
  GO111MODULE=on

install:
  - make install

script:
  - make test

before_install:
  - go get github.com/mitchellh/gox

after_success:
  - if [ ! -z "$TRAVIS_TAG" ]; then make releases; fi

